version: "2"
services: 
    node:
        container_name: node
        build: "./node"
        links: 
            - redis

    redis:
        container_name: redis
        image: redis
        volumes: 
            - ./data:/data
        ports: 
            - "6379:6379"
